// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { identity } from "npm:@/data/portfolio";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who is Rohit Sen",
  description: "Return Rohit Sen's identity: name, role, tagline, location, focus, and status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(identity, null, 2) }],
    structuredContent: { identity }
  })
});

// src/lib/mcp/tools/get-about.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { aboutParagraphs, identity as identity2 } from "npm:@/data/portfolio";
var get_about_default = defineTool2({
  name: "get_about",
  title: "Get about section",
  description: "Return the About section: bio paragraphs and top-line identity for Rohit Sen.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: aboutParagraphs.join("\n\n") }],
    structuredContent: { identity: identity2, about: aboutParagraphs }
  })
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
import { skills } from "npm:@/data/portfolio";
var categories = ["frontend", "backend", "security", "cloud", "other", "all"];
var list_skills_default = defineTool3({
  name: "list_skills",
  title: "List skills",
  description: "List Rohit Sen's technical skills, optionally filtered by category (frontend, backend, security, cloud, other, or all).",
  inputSchema: {
    category: z.enum(categories).optional().describe("Which skill category to return. Defaults to 'all'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const cat = category ?? "all";
    const data = cat === "all" ? skills : { [cat]: skills[cat] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { skills: data }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { projects } from "npm:@/data/portfolio";
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "List projects",
  description: "List Rohit Sen's portfolio projects with names and short descriptions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
    structuredContent: { projects }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { contact, socialLinks } from "npm:@/data/portfolio";
var get_contact_default = defineTool5({
  name: "get_contact",
  title: "Get contact info",
  description: "Return Rohit Sen's public contact info: email, GitHub, LinkedIn, and social links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify({ contact, socialLinks }, null, 2) }],
    structuredContent: { contact, socialLinks }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "rohit-sen-portfolio-mcp",
  title: "Rohit Sen Portfolio MCP",
  version: "0.1.0",
  instructions: "Public tools that expose Rohit Sen's portfolio content: identity, about, skills, projects, and contact info. Use these to answer questions about Rohit's background, expertise, and how to reach him.",
  tools: [whoami_default, get_about_default, list_skills_default, list_projects_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
